stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - powershell -Command "Remove-Item -Recurse -Force .gradle -ErrorAction SilentlyContinue"
    - powershell -Command "Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue"
    - ./gradlew clean build -x test
  artifacts:
    paths:
      - build/libs/
test-job:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - build/test-results/test/
      - build/reports/tests/test/

deploy-prod:
  stage: deploy
  script:
    - echo "Deploying branch $CI_COMMIT_BRANCH to production..."
  environment: production
  only:
    - main